version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    networks:
      - mysqlnet
  mysql:
      image: mysql
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=123456
      volumes:
        - mysql:/var/lib/mysql
        - mysql_config:/etc/mysql
      networks:
        - mysqlnet

volumes:
  mysql:
  mysql_config:

networks:
  mysqlnet:
    driver: bridge
